set_property SRC_FILE_INFO {cfile:C:/Users/benny/Documents/CalPoly/cpe/133/adders/half_adder_sop/half_adder_sop.srcs/constrs_1/new/HalfAdderSOP_Constraints.xdc rfile:../../../half_adder_sop.srcs/constrs_1/new/HalfAdderSOP_Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {OP_A}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {OP_B}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports {SUM}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {CO}]
